### ISSUE TITLE
Switch to Python 3.6 or 3.7?

### ISSUE THREAD

**Issue by mr-c** [ohsu-comp-bio/cwl-tes#22]
@adamstruck What do you think? Would be nice to be modern. With Anaconda/Conda I think there is no reason to stick to Python 2.7

**Comment by adamstruck** [comment]
The project already supports 3.5 and 3.6. I haven't tried testing against 3.7, but I assume it would work. Am I missing something?

**Comment by psafont** [comment]
I think Michael wants to drop support for at least Python 2.7. (and maybe 3.4 and 3.5? not sure)

Regarding the CI, 3.7 support in Travis is a bit iffy, but something like [this commit](https://github.com/jmsv/ety-python/commit/ae8a330bda2d911cfedb3b1f08bd3e4c161e0ea3) works.

**Comment by mr-c** [comment]
@psafont Yes, at least drop 2.x

Python 3.4 end of life is 2019-03-16

https://devguide.python.org/#status-of-python-branches

These days it is no problem to install a newer Python version, so I suggest targeting 3.6 or 3.7.

**Comment by mr-c** [comment]
Fixed in https://github.com/ohsu-comp-bio/cwl-tes/commit/e0b56d27a6dd4bbc03a0879c37ecd0b41fd1c052 / https://github.com/ohsu-comp-bio/cwl-tes/pull/40
