### ISSUE TITLE
Move cwl-tes repo to a different organization?

### ISSUE THREAD

**Issue by mr-c** [ohsu-comp-bio/cwl-tes#28]
As requested by @susheel 

It is fine by me, but where to move?

**Comment by susheel** [comment]
@mr-c Not sure?
@rishidev - GA4GH perhaps?

**Comment by geoffjentry** [comment]
@susheel Can I infer from your suggestion that we should move all implementations of all GA4GH APIs to the GA4GH org?

**Comment by susheel** [comment]
@geoffjentry No, not necessarily. Just a suggestion specifically for cwl-tes

**Comment by geoffjentry** [comment]
@susheel Why would cwl-tes be different from any other implementation here?

**Comment by susheel** [comment]
@geoffjentry For cwl-tes, GA4GH was just a suggestion, which I now retract.

I think ELIXIR is more appropriate here, as we are the main users of this codebase.

**Comment by tetron** [comment]
Yes, the sponsoring organization (ELIXIR) should probably own it.

**Comment by adamstruck** [comment]
Since this project was created by OHSU, it would make sense to transfer ownership back to one of our organizations.

**Comment by susheel** [comment]
@adamstruck Happy with that too. Would we have the ability to fork and send you PRs?

**Comment by adamstruck** [comment]
@susheel yes of course

**Comment by mr-c** [comment]
@adamstruck tell me the GitHub organization and I'll initiate the move

**Comment by adamstruck** [comment]
@mr-c the organization is https://github.com/ohsu-comp-bio/

**Comment by mr-c** [comment]
@adamstruck you'll need to remove it rename your for of cwl-tes and temporarily give me permission to create repository in your organization. Or I can give you admin rights here..

**Comment by adamstruck** [comment]
@mr-c could you give me temporary admin rights to this repo so I can move it?

**Comment by mr-c** [comment]
@adamstruck Done. Do you see the option at the bottoms of https://github.com/common-workflow-language/cwl-tes/settings

**Comment by adamstruck** [comment]
@mr-c I do not see the option. It says `Organization members cannot transfer repositories`.

**Comment by mr-c** [comment]
@adamstruck 
> Members can now delete or transfer repositories. 

Look again?

**Comment by adamstruck** [comment]
@mr-c Done. Thanks!
